<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>deepseek_copilot</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="copiloticon.svg" />
    <PackageReference Include="Svg.Skia" Version="5.1.1" />
    <PackageReference Include="KBEHtool" Version="0.5.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.*" />
    <!-- <ProjectReference Include="..\..\..\Documents\GitHub\DanKeJson\DanKeJson\DanKeJson.csproj" /> -->
    <PackageReference Include="DanKeJson" Version="1.5.0" />
  </ItemGroup>

</Project>
